# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NwIVqTiIXDq5h-x-5TSSLWEYn6oZIpF7
"""

import gradio as gr
import pandas as pd
import joblib

# Load your saved model and scaler
lr_model = joblib.load("lr_model.joblib")
scaler = joblib.load("scaler.joblib")

# Mapping for dropdowns to encoded values
gender_map = {"Female": 0, "Male": 1}
geography_map = {"France": (0,0), "Spain": (1,0), "Germany": (0,1)}

# Function to predict churn
def predict_customer(CreditScore, Age, Tenure, Balance, NumOfProducts, IsActiveMember,
                     EstimatedSalary, Complain, Satisfaction_Score, Card_Type, Point_Earned,
                     Gender, Geography):

    # Convert dropdowns to encoded numeric values
    Gender_1 = gender_map[Gender]
    Geography_1, Geography_2 = geography_map[Geography]

    # Prepare DataFrame in the correct order
    X = pd.DataFrame([[CreditScore, Age, Tenure, Balance, NumOfProducts, IsActiveMember,
                       EstimatedSalary, Complain, Satisfaction_Score, Card_Type, Point_Earned,
                       Gender_1, Geography_1, Geography_2]],
                     columns=['CreditScore','Age','Tenure','Balance','NumOfProducts','IsActiveMember',
                              'EstimatedSalary','Complain','Satisfaction Score','Card Type','Point Earned',
                              'Gender_1','Geography_1','Geography_2'])

    # Scale features and predict
    X_scaled = scaler.transform(X)
    pred = lr_model.predict(X_scaled)[0]
    prob = lr_model.predict_proba(X_scaled)[:,1][0]

    return f"Prediction: {pred} (0=stay, 1=exit), Probability of exiting: {prob:.2f}"

# Define Gradio inputs
inputs = [
    gr.Number(label="CreditScore"),
    gr.Number(label="Age"),
    gr.Number(label="Tenure"),
    gr.Number(label="Balance"),
    gr.Number(label="NumOfProducts"),
    gr.Number(label="IsActiveMember (0 or 1)"),
    gr.Number(label="EstimatedSalary"),
    gr.Number(label="Complain (0 or 1)"),
    gr.Number(label="Satisfaction Score"),
    gr.Number(label="Card Type"),
    gr.Number(label="Point Earned"),
    gr.Dropdown(label="Gender", choices=list(gender_map.keys())),
    gr.Dropdown(label="Geography", choices=list(geography_map.keys()))
]

# Define output
outputs = gr.Textbox(label="Prediction")

# Launch the Gradio app
gr.Interface(fn=predict_customer, inputs=inputs, outputs=outputs).launch()